[package]
name = "libbinder-raw"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
bytemuck_derive = "1.10.2"
enumflags2 = "0.7.12"
nix = { version = "0.30.1", features = ["ioctl", "mman"] }
num_enum = "0.7.5"
