[package]
name = "libbinder-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
delegate = "0.13.5"
libbinder = { version = "0.1.0", path = "../libbinder" }
libbinder-raw = { version = "0.1.0", path = "../libbinder-raw" }
nix = "0.30.1"
sealed = "0.6.0"
thread_local = "1.1.9"
