[package]
name = "libbinder"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
enumflags2 = "0.7.12"
libbinder-raw = { version = "0.1.0", path = "../libbinder-raw" }
nix = { version = "0.30.1", features = ["poll"] }
