[package]
name = "libbinder"
version = "0.1.0"
edition = "2024"

[dependencies]
enumflags2 = "0.7.12"
libbinder-raw = { version = "0.1.0", path = "../libbinder-raw" }
yoke = { version = "0.8.1", features = ["derive"] }
